version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
     - "27017:27017"
    container_name: mongo-docker
    network_mode: host

  eureka-service:
    build: eurekaservice/
    restart: always
    network_mode: host
    container_name: eureka-service-docker
    ports:
     - "9091:9091"
    expose:
     - 9091

  config-server:
    build: configserver/
    restart: always
    network_mode: host
    container_name: config-server-docker
    ports:
      - "8099:8099"
    expose:
      - 8099

  track-service:
    build: MuzixApplicationMongodTrack/
    restart: always
    network_mode: host
    hostname: localhost
    container_name: track-service-docker
    depends_on:
      - config-server
      - eureka-service
      - mongo

    ports:
      - "8096:8096"
    expose:
      - 8096

  user-service:
    build: MuzixApplicationMongodUser/
    restart: always
    network_mode: host
    hostname: localhost
    container_name: user-service-docker
    depends_on:
      - config-server
      - eureka-service
      - mongo

    ports:
      - "8095:8095"
    expose:
      - 8095

  zuul-service:
    build: micro-service-zulu/
    restart: always
    network_mode: host
    container_name: zuul-service-docker
    ports:
      - "8097:8097"
    expose:
      - 8097
